CREATE DATABASE VETPROCARE;
USE VETPROCARE;
SHOW TABLES;
CREATE TABLE CLIENT 
( CLIENT_ID VARCHAR(15),FIRST_NAME VARCHAR(20),LAST_NAME VARCHAR(20),EMAIL VARCHAR(25) UNIQUE,PHONE_NUMBER CHAR(10),ADDRESS VARCHAR(50),
PASSWORD VARCHAR(8),PRIMARY KEY(CLIENT_ID));

CREATE TABLE PET
(PET_ID VARCHAR(50),CLIENT_ID VARCHAR(15),PET_NAME VARCHAR(20),SPECIES VARCHAR(20),BREED varchar(20),
PRIMARY KEY(PET_ID,CLIENT_ID),FOREIGN KEY(CLIENT_ID) references CLIENT(CLIENT_ID) ON DELETE CASCADE);

CREATE TABLE APPOINTMENT
(APPOINTMENT_ID VARCHAR(25),CLIENT_ID VARCHAR(50),PET_ID VARCHAR(50),APPOINTMENT_DATE varchar(15),STATUS1 VARCHAR(20),reason varchar(100),token int,PRIMARY KEY(APPOINTMENT_ID),FOREIGN KEY(CLIENT_ID) REFERENCES CLIENT(CLIENT_ID) ON DELETE CASCADE,FOREIGN KEY(PET_ID) REFERENCES PET(PET_ID) ON DELETE CASCADE);


create view appointment_details as
select p.client_id,p.pet_name,p.pet_id,a.appointment_date,token,reason,status1
from pet p , appointment a 
where p.pet_id = a.pet_id ;
